export const ADD_CART_PRODUCTS = "ADD_CART_PRODUCTS";
export const DELETE_CART_PRODUCTS = "DELETE_CART_PRODUCTS";
export const ADD_CART_PRICE = "ADD_CART_PRICE";
export const DELETE_CART_PRICE = "DELETE_CART_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_TO_CART = "DELETE_TO_CART";