export const ADD_WISHLIST_PRODUCTS = "ADD_WISHLIST_PRODUCTS";
export const DELETE_WISHLIST_PRODUCTS = "DELETE_WISHLIST_PRODUCTS";
export const DELETE_TO_WISHLIST = "DELETE_TO_WISHLIST";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";